# Generated by Django 5.1.1 on 2024-09-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subtitle_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='content',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
