# Generated by Django 5.1.1 on 2024-09-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_subtitle_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
